deneme

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -45,7 +45,7 @@ RUN chmod +x Xilinx_Unified_2022.1_0420_0327_Lin64.bin
 RUN ls -lh Xilinx_Unified_2022.1_0420_0327_Lin64.bin
 
 # Run the Vivado installer in batch mode (headless mode)
-RUN ./Xilinx_Unified_2022.1_0420_0327_Lin64.bin --confirm --target /opt/Xilinx -b Install || { echo "Vivado installation failed"; exit 1; }
+RUN ./Xilinx_Unified_2022.1_0420_0327_Lin64.bin --confirm --nox11 -- --target /opt/ || { echo "Vivado installation failed"; exit 1; }
 
 # Check if Vivado is installed correctly
 RUN ls -lah /opt/Xilinx
